services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shu-tictactoe-backend
    ports:
      - "3001:3001"
    volumes:
      - backend-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shu-tictactoe-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:3001/api

volumes:
  backend-data:
    driver: local
